### ISSUE TITLE
Generic/fallback avatar image displaying over user's avatar

### ISSUE THREAD

**Issue by ghost** [tersiswilvin/Roblox-2019-Old-Theme#16]
### Browser

Google Chrome

### Channel

Experimental

### Page URL

https://www.roblox.com/home

### Describe the Problem

On the friends list, the generic avatar icon is showing behind my friends' avatar.
![image](https://github.com/tersiswilvin/Roblox-2019-Old-Theme/assets/77752310/6e29ac98-d0b1-459a-a6a4-c7e03da4297b)

**Comment by tersiswilvin** [comment]
Hi [MX-Mic](https://github.com/MX-Mic), this is technically intentional as when I was looking through archives lately for 2019 apparently they had the generic avatar behind the avatar this was before roblox updated thumbnails to have different poses and different angles so you couldn't see the icon unless it the image didn't load.

**Comment by tersiswilvin** [comment]
However if you find this annoying I can add an option to restore what the legacy versions had (a solid background color).

**Comment by ghost** [comment]
That would be good if you could do this. Surprisingly, I've never heard of this behaviour before or even seen it!

**Comment by tersiswilvin** [comment]
Added an option for the Pre1.3 background color in 1.3.1.

**Comment by ghost** [comment]
> Added an option for the Pre1.3 background color in 1.3.1.

I noticed as I looked at the commits and found on the CSS that a new @var declaration was added for the settings and I immediately turned it on. I will close the issue, unless you need to comment something else!
