### ISSUE TITLE
Why is there some "2015" stuff but not all 2015 stuff, also for 2020+, and bascially every

### ISSUE THREAD

**Issue by githubberguy** [tersiswilvin/Roblox-2019-Old-Theme#58]
### Type

CSS

### Describe the Feature

so i want it so in every option i find 2015 (and the other years) beacuse if i want to make 2015 but can't beacuse there isnt many 2015 stuff, it means i have to scroll to the depths to find a working 2015 roblox style

**Comment by githubberguy** [comment]
probably useless, tell me if i need to close

**Comment by ghost** [comment]
The reason is almost certainly likely because anything below 2016 isn't really compatible to a good enough standard with the modern site, meaning we have to use JS in most cases, as that allows you to move elements and manipulate or change stuff to a much greater limit than what CSS allows. Using CSS alone would probably make it look not very accurate!

**Comment by githubberguy** [comment]
ok, thanks
